# Generated by Django 6.0.4 on 2026-05-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KillFeed',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('killer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('killer_name', models.CharField(max_length=255)),
                ('killer_team', models.CharField(max_length=255)),
                ('victim_id', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_name', models.CharField(max_length=255)),
                ('victim_team', models.CharField(max_length=255)),
                ('weapon', models.CharField(max_length=255)),
                ('is_knock', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverlayConfig',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('show_rankings', models.BooleanField(default=True)),
                ('show_kill_feed', models.BooleanField(default=True)),
                ('show_team_status', models.BooleanField(default=True)),
                ('show_match_info', models.BooleanField(default=True)),
                ('show_player_cam', models.BooleanField(default=False)),
                ('theme', models.CharField(default='default', max_length=100)),
                ('animations_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('video_url', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('logo', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='standing', serialize=False, to='core.team')),
                ('rank', models.IntegerField()),
                ('total_points', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('placement_points', models.IntegerField(default=0)),
                ('kill_points', models.IntegerField(default=0)),
                ('wwcd', models.IntegerField(default=0)),
                ('matches_json', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('knocked', 'Knocked'), ('eliminated', 'Eliminated')], max_length=20)),
                ('kills', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('photo', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team')),
            ],
        ),
    ]
